# -*- coding: utf-8 -*-
"""credit_projectG1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ptKaTJTYaLq-aJqZXx4wbHpB01G_7AgV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('project_dataset.csv')
df

df.head()

df.tail()

df.info()

df.describe(include="all")

"""preprocessing"""

df.isnull().sum()

"""there is no null values"""

df.isna()

df.duplicated().sum()

"""boxplotting"""

numerical_features = ['Income','Credit_Score','Loan_Amount','Repayment_Period']

for feature in numerical_features:
    sns.boxplot(df[feature])
    plt.title(f'Box Plot of {feature}')
    plt.show()

#Decision: Remove Outliers from all numerical features
for feature in numerical_features:
    q1, q3 = np.percentile(df[feature], [25, 75])
    iqr = q3 - q1
    minimum = q1 - 1.5 * iqr
    maximum = q3 + 1.5 * iqr
    df = df[(df[feature] >= minimum) & (df[feature] <= maximum)]
    print(f"Outliers removed from {feature}")
df

#Label Encode Categorical Features
from sklearn.preprocessing import LabelEncoder
le_employment = LabelEncoder()
df['Employment_Status'] = le_employment.fit_transform(df['Employment_Status'])
le_eligible = LabelEncoder()
df['Eligible'] = le_eligible.fit_transform(df['Eligible'])
df

#Feature Scaling- Numerical Only - MinMax Scaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[numerical_features] = scaler.fit_transform(df[numerical_features])
df

# Dataset Splitting for Training and testing
from sklearn.model_selection import train_test_split
X = df.drop('Eligible', axis=1)
y = df['Eligible']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state = 42)

# df size: 8494x14
#X size : 8494x13
#y size: 8494x1
#X_train = 6795x13
#Y_train = 6795x1
#X_test =1699x13
#y_test = 1699x1

print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)
print("Shape of y_train: ", y_train.shape)
print("Shape of y_test: ", y_test.shape)

# Model Selection Training - Logistic Regression
from sklearn.linear_model import LogisticRegression  #class  import
lr = LogisticRegression() #object / instance creation
lr.fit(X_train, y_train) # Training

X_test

y_test

y_pred = lr.predict(X_test) #Evaluation
y_pred

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=le_eligible.classes_, yticklabels=le_eligible.classes_)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

#Random Forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

import pickle
pickle.dump(rf, open('model.pkl', 'wb'))
pickle.dump(scaler, open('scaler.pkl', 'wb'))
pickle.dump(le_employment, open('le_employment.pkl', 'wb'))
pickle.dump(le_eligible, open('le_eligible.pkl', 'wb'))